"""
build-content.py — Regenerate content sections of index.html from
the structured files in data/. Run from the acting/ root:

    python .scripts/build-content.py

Inputs (split across per-topic files so the Decap sidebar lists each
as a separate clickable entry):
  data/bio.md             — bio paragraph (with optional front-matter)
  data/hero.yml           — hero slideshow (paired image + 2-line quote per slide)
  data/about.yml          — RIZZO definition + pronunciation audio + pull quotes
  data/training.yml       — training entries

  Credits collection:
    data/film.yml         — film credits     (entries:)
    data/tv.yml           — tv credits       (entries:)
    data/theater.yml      — theater credits  (entries:)
    data/commercial.yml   — commercial credits (entries:)
    data/credits-tabs.yml — credit tab show/hide toggles (tabs:)

  Stats / Skills / Influences collection:
    data/physical.yml       — appearance (age, height, eyes, hair, ...)
    data/measurements.yml   — wardrobe sizes
    data/languages.yml      — spoken languages (entries:)
    data/licensing.yml      — documents + union + local_hire
    data/skills.yml         — Key Skills paragraph (text:)
    data/favorite-films.yml — favorite films (entries:)
    data/inspirations.yml   — directors/creators that inform work (entries:)

  Contact, Socials, Reel collection:
    data/contact.yml      — email + contact_section copy
    data/socials.yml      — social pills (entries:)
    data/reel.yml         — reel embed (url, file, placeholder)

  Site Settings collection:
    data/seo.yml          — SEO + Open Graph + Twitter card
    data/favicon.yml      — favicon source image
    data/analytics.yml    — GA4 measurement ID
    data/menu.yml         — top-nav items (entries:)
    data/footer.yml       — footer text + show_version
    data/sections.yml     — section show/hide toggles (about/profile_bio/...)

Updates these EDIT-marked blocks in index.html (and only these):
  EDIT: bio                   ← from data/bio.md
  EDIT: training              ← from data/training.yml
  EDIT: print-training        ← from data/training.yml
  EDIT: film-credits          ← from data/film.yml
  EDIT: print-film-credits    ← from data/film.yml
  EDIT: tv-credits            ← from data/tv.yml
  EDIT: print-tv-credits      ← from data/tv.yml
  EDIT: theater-credits       ← from data/theater.yml
  EDIT: print-theater-credits ← from data/theater.yml
  EDIT: commercial-credits    ← from data/commercial.yml
  EDIT: credits-tabs          ← from data/credits-tabs.yml (tabs)
  EDIT: hero-slides           ← from data/hero.yml
  EDIT: hero-quotes           ← from data/hero.yml
  EDIT: rizzo-definition      ← from data/about.yml
  EDIT: pull-quote            ← from data/about.yml
  EDIT: physical              ← from data/physical.yml
  EDIT: languages             ← from data/languages.yml
  EDIT: print-languages       ← from data/languages.yml
  EDIT: measurements          ← from data/measurements.yml
  EDIT: licensing             ← from data/licensing.yml
  EDIT: print-licensing       ← from data/licensing.yml
  EDIT: skills                ← from data/skills.yml
  EDIT: print-skills          ← from data/skills.yml
  EDIT: favorite-films        ← from data/favorite-films.yml
  EDIT: inspirations          ← from data/inspirations.yml
  EDIT: print-stats           ← from data/physical.yml + data/measurements.yml
  EDIT: socials               ← from data/socials.yml
  EDIT: reel                  ← from data/reel.yml
  EDIT: contact-section       ← from data/contact.yml (contact_section)
  EDIT: site-meta             ← from data/seo.yml (SEO subtree)
  EDIT: og-tags               ← from data/seo.yml (OG + Twitter)
  EDIT: ga4                   ← from data/analytics.yml
  EDIT: menu                  ← from data/menu.yml
  EDIT: footer                ← from data/footer.yml
  EDIT: section-visibility    ← from data/sections.yml (emits CSS rules to hide off sections)

NOTE: the JSON-LD Movie nodes in index.html are NOT regenerated by this
script (they cross-reference Person via @id which would tangle the
generation). When you add or remove a film credit, also update the
Movie nodes inside the EDIT: json-ld block manually — see EDITING.md.

Idempotent: running with unchanged data files produces unchanged output.
"""
from pathlib import Path
import re
import html as html_lib

try:
    import yaml
except ImportError:
    print("Install PyYAML first:  pip install PyYAML")
    raise SystemExit(1)

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
DATA = ROOT / "data"

# Single source of truth for the version chip displayed in the footer.
# Bump this when you release a new version of the site (and add the
# matching ### v0.X.Y entry to README.md changelog).
SITE_VERSION = "v0.7.28"


# ---------- helpers ----------

def esc(s):
    """HTML-escape a value safely. Returns empty string for None."""
    if s is None:
        return ""
    return html_lib.escape(str(s), quote=False)


def md_inline(s):
    """Tiny markdown subset for the bio: **bold** and *italic*."""
    s = esc(s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
    return s


def replace_block(html, marker, new_inner):
    """Replace content between <!-- EDIT: marker [...] --> and
    <!-- /EDIT: marker -->. The marker comments themselves are preserved.
    The EDIT comment may span multiple lines and contain `>` chars in
    its description, so the opening-comment match uses .*? rather than
    [^>]* and the whole pattern runs with DOTALL."""
    pattern = re.compile(
        r"(<!--\s*EDIT:\s*" + re.escape(marker) + r"\b.*?-->)"
        r"(.*?)"
        r"(<!--\s*/EDIT:\s*" + re.escape(marker) + r"\s*-->)",
        re.DOTALL,
    )
    if not pattern.search(html):
        raise SystemExit(f"Marker not found in index.html: EDIT: {marker}")
    return pattern.sub(
        lambda m: m.group(1) + new_inner + m.group(3),
        html,
        count=1,
    )


# ---------- generators ----------

def load_bio_body():
    text = (DATA / "bio.md").read_text(encoding="utf-8")
    # Strip front-matter if present
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            text = parts[2]
    return text.strip()


def gen_bio():
    body = load_bio_body()
    return (
        "\n"
        '        <p class="profile-bio">\n'
        "          " + md_inline(body).replace("\n", "\n          ") + "\n"
        "        </p>\n"
        "        "
    )


# Lucide-style line-icon SVG paths (24x24 viewBox). One per training "kind"
# value. The badge CSS strokes them with currentColor and sets width/height,
# so these paths only need d-data. Keep the keys aligned with the Decap
# select options in admin/config.yml > training > kind > options.
TRAINING_ICONS = {
    "Workshop":     '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94"/>',
    "Class":        '<path d="M2 3h6a4 4 0 0 1 4 4v13a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v13a3 3 0 0 1 3-3h7z"/>',
    "Course":       '<path d="M2 3h6a4 4 0 0 1 4 4v13a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v13a3 3 0 0 1 3-3h7z"/>',
    "Intensive":    '<path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0"/>',
    "Masterclass":  '<circle cx="12" cy="9" r="6"/><path d="M15.5 13.5 17 22l-5-3-5 3 1.5-8.5"/>',
    "Conservatory": '<path d="M3 21h18M5 21V8l7-4 7 4v13M9 9v4M12 9v4M15 9v4M9 17v4M15 17v4"/>',
    "Showcase":     '<path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="22"/>',
    "Revue":        '<circle cx="9" cy="11" r="5"/><circle cx="15" cy="13" r="5"/>',
    "Coaching":     '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="m16 11 2 2 4-4"/>',
}


def kind_badge(kind, leading_space=False):
    """Render a training kind/badge <span> with its matching line icon.
    Returns '' when kind is empty. leading_space=True prepends a space so the
    badge sits cleanly after another inline element (used in the print path)."""
    kind = (kind or "").strip()
    if not kind:
        return ""
    icon = TRAINING_ICONS.get(kind, "")
    svg = f'<svg viewBox="0 0 24 24" aria-hidden="true">{icon}</svg>' if icon else ""
    lead = " " if leading_space else ""
    return f'{lead}<span class="kind">{svg}{esc(kind)}</span>'


def gen_training_screen(training):
    lines = []
    for e in training["entries"]:
        sub_parts = [p for p in (e.get("teachers", ""), e.get("school", "")) if p]
        sub = " &middot; ".join(esc(p) for p in sub_parts)
        kind_html = kind_badge(e.get("kind"))
        lines.append(
            '          <li><span class="label">'
            + esc(e["title"])
            + '</span>'
            + kind_html
            + '<span class="sub">'
            + sub
            + "</span></li>"
        )
    return (
        "\n      <div class=\"panel col-6\">\n"
        "        <h4>Education / Training</h4>\n"
        "        <ul>\n"
        + "\n".join(lines)
        + "\n        </ul>\n"
        "      </div>\n      "
    )


def gen_training_print(training):
    lines = []
    for e in training["entries"]:
        sub_parts = [p for p in (e.get("teachers", ""), e.get("school", "")) if p]
        sub = " &middot; ".join(esc(p) for p in sub_parts)
        kind_html = kind_badge(e.get("kind"), leading_space=True)
        lines.append(
            f"      <div><strong>{esc(e['title'])}{kind_html}</strong><em>{sub}</em></div>"
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Training</h2>\n"
        "    <div class=\"rs-training-list\">\n"
        + "\n".join(lines)
        + "\n    </div>\n"
        "  </div>\n  "
    )


# Order of the credit tabs (slug → display label). The tabs strip is
# rendered in this order; the first tab whose visibility is true gets
# the active state. Hidden tabs are omitted from both the strip and
# the panel area below.
TAB_ORDER = [
    ("film",       "Film"),
    ("tv",         "TV"),
    ("theater",    "Theater"),
    ("commercial", "Commercial"),
]


def _visible_tabs(credits):
    vis = credits.get("tab_visibility") or {}
    # Default to visible if a flag is omitted from credits.yml; commercial
    # defaults to hidden (placeholder until real entries exist).
    defaults = {"film": True, "tv": True, "theater": True, "commercial": False}
    return [
        (slug, label)
        for slug, label in TAB_ORDER
        if vis.get(slug, defaults.get(slug, True))
    ]


def _is_first_visible(credits, slug):
    vt = _visible_tabs(credits)
    return bool(vt) and vt[0][0] == slug


def gen_credits_tabs(credits):
    visible = _visible_tabs(credits)
    if not visible:
        return "\n    <div class=\"tabs\" role=\"tablist\"></div>\n    "
    buttons = []
    for i, (slug, label) in enumerate(visible):
        active = " active" if i == 0 else ""
        buttons.append(
            f'      <button class="tab{active}" data-tab="{esc(slug)}" role="tab">{esc(label)}</button>'
        )
    return (
        "\n    <div class=\"tabs\" role=\"tablist\">\n"
        + "\n".join(buttons)
        + "\n    </div>\n    "
    )


def gen_film_screen(films, is_active=True):
    cls = "tab-panel active" if is_active else "tab-panel"
    rows = []
    for f in films:
        title = esc(f["title"])
        href = (
            f"https://www.imdb.com/title/{esc(f['imdb'])}/"
            if f.get("imdb")
            else f"https://www.imdb.com/find/?s=tt&q={title.replace(' ', '+')}"
        )
        rows.append(
            f'          <tr><td class="title"><a href="{href}" target="_blank" rel="noopener" title="View on IMDB">{title}</a> '
            f'<span class="sub" style="color:var(--dim)">({esc(f["type"])}, {esc(f["year"])})</span></td>'
            f'<td class="role">{esc(f["role"])}</td>'
            f'<td class="dir">dir. {esc(f["director"])}</td></tr>'
        )
    return (
        f'\n    <div class="{cls}" id="film">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Director</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_film_print(films):
    rows = []
    for f in films:
        rows.append(
            f'      <tr><td class="t">{esc(f["title"])} '
            f'<em style="color:#888;font-style:normal">({esc(f["type"])}, {esc(f["year"])})</em></td>'
            f'<td class="r">{esc(f["role"])}</td>'
            f'<td class="d">dir. {esc(f["director"])}</td></tr>'
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Film</h2>\n"
        "    <table class=\"rs-table\">\n"
        + "\n".join(rows)
        + "\n    </table>\n"
        "  </div>\n  "
    )


def gen_tv_screen(tv, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    rows = []
    for t in tv:
        rows.append(
            f'          <tr><td class="title">{esc(t["title"])} '
            f'<span class="sub" style="color:var(--dim)">({esc(t["season"])})</span></td>'
            f'<td class="role">{esc(t["role"])}</td>'
            f'<td class="dir">{esc(t["network"])}</td></tr>'
        )
    return (
        f'\n    <div class="{cls}" id="tv">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Network</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_tv_print(tv):
    rows = []
    for t in tv:
        rows.append(
            f'      <tr><td class="t">{esc(t["title"])} '
            f'<em style="color:#888;font-style:normal">({esc(t["season"])})</em></td>'
            f'<td class="r">{esc(t["role"])}</td>'
            f'<td class="d">{esc(t["network"])}</td></tr>'
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Television</h2>\n"
        "    <table class=\"rs-table\">\n"
        + "\n".join(rows)
        + "\n    </table>\n"
        "  </div>\n  "
    )


def _theater_resolve(theater, footnotes_doc):
    """Returns (rows, active_footnotes) where each row is a dict of resolved
    cell values, and active_footnotes is the list of {marker, long} pairs
    whose marker appears on at least one entry."""
    strict = bool(footnotes_doc.get("strict_mode", False))
    notes = footnotes_doc.get("footnotes") or []
    by_marker = {(n.get("marker") or ""): n for n in notes}

    rows = []
    used_markers = []
    for t in theater:
        marker = (t.get("footnote") or "").strip()
        if strict and marker and marker in by_marker:
            # Strict Mode: swap venue for the footnote's short form
            venue_text = by_marker[marker].get("short") or t["venue"]
            venue_marker = ""
        else:
            venue_text = t["venue"]
            venue_marker = marker if marker in by_marker else ""
        if venue_marker and venue_marker not in used_markers:
            used_markers.append(venue_marker)
        rows.append({
            "production": t["production"],
            "role": t["role"],
            "venue": venue_text,
            "marker": venue_marker,
        })

    active_footnotes = [] if strict else [
        {"marker": m, "long": by_marker[m].get("long", "")} for m in used_markers
    ]
    return rows, active_footnotes


def gen_theater_screen(theater, footnotes_doc, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    resolved, active_footnotes = _theater_resolve(theater, footnotes_doc)
    rows = []
    for t in resolved:
        role_cell = (
            f'Sketches: <span style="color:var(--muted);font-weight:400">{esc(t["role"])}</span>'
            if "," in t["role"]
            else esc(t["role"])
        )
        marker_html = (
            f'<sup class="venue-mark">{esc(t["marker"])}</sup>'
            if t["marker"] else ""
        )
        rows.append(
            f'          <tr><td class="title">{esc(t["production"])}</td>'
            f'<td class="role">{role_cell}</td>'
            f'<td class="dir">{esc(t["venue"])}{marker_html}</td></tr>'
        )
    foot_html = ""
    if active_footnotes:
        items = "\n".join(
            f'        <li><span class="m">{esc(n["marker"])}</span> {esc(n["long"])}</li>'
            for n in active_footnotes
        )
        foot_html = (
            '\n      <ul class="theater-footnotes">\n'
            + items
            + "\n      </ul>"
        )
    return (
        f'\n    <div class="{cls}" id="theater">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Production</th><th>Role / Sketches</th><th>Stage</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>"
        + foot_html
        + "\n    </div>\n    "
    )


def gen_commercial_screen(commercial, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    if not commercial:
        body = (
            '          <tr><td class="title" colspan="3" '
            'style="text-align:center;color:var(--muted)">Available upon request.</td></tr>'
        )
    else:
        rows = []
        for c in commercial:
            rows.append(
                f'          <tr><td class="title">{esc(c.get("title", ""))}</td>'
                f'<td class="role">{esc(c.get("role", ""))}</td>'
                f'<td class="dir">{esc(c.get("brand", ""))}</td></tr>'
            )
        body = "\n".join(rows)
    return (
        f'\n    <div class="{cls}" id="commercial">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Brand</th></tr></thead>\n"
        "        <tbody>\n"
        + body + "\n"
        "        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_theater_print(theater, footnotes_doc):
    resolved, active_footnotes = _theater_resolve(theater, footnotes_doc)
    rows = []
    for t in resolved:
        marker_html = (
            f'<sup>{esc(t["marker"])}</sup>' if t["marker"] else ""
        )
        rows.append(
            f'      <tr><td class="t">{esc(t["production"])}</td>'
            f'<td class="r">{esc(t["role"])}</td>'
            f'<td class="d">{esc(t["venue"])}{marker_html}</td></tr>'
        )

    foot_html = ""
    if active_footnotes:
        lines = [
            f'<span class="rs-theater-foot-row"><span class="m">{esc(n["marker"])}</span> {esc(n["long"])}</span>'
            for n in active_footnotes
        ]
        foot_html = (
            '\n    <p class="rs-theater-foot">'
            + " &nbsp; ".join(lines)
            + "</p>"
        )

    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Theater &middot; Sketch / Improv</h2>\n"
        "    <table class=\"rs-table rs-theater\">\n"
        + "\n".join(rows)
        + "\n    </table>"
        + foot_html
        + "\n  </div>\n  "
    )


# ---------- hero (slides + quotes) ----------

def gen_hero_slides(hero):
    lines = []
    for s in hero["slides"]:
        video = s.get("video", "").strip() if s.get("video") else ""
        photo = s.get("photo", "").strip() if s.get("photo") else ""
        if video:
            # Note: no `loop` attribute - the JS rotator waits for the
            # video's `ended` event before advancing to the next slide,
            # so videos play their full length once. Muted by default
            # (autoplay requirement); the floating volume control unmutes.
            lines.append(
                f'    <video class="hero-slide" muted playsinline preload="metadata">'
                f'<source src="{esc(video)}" type="video/mp4">'
                f'</video>'
            )
        else:
            lines.append(
                f'    <div class="hero-slide" style="background-image:url(\'{esc(photo)}\')"></div>'
            )
    return "\n  <div class=\"hero-slides\" aria-hidden=\"true\">\n" + "\n".join(lines) + "\n  </div>\n  "


def gen_hero_quotes(hero):
    lines = []
    for s in hero["slides"]:
        lines.append(
            f"      <span>{esc(s['quote_line_1'])}<br>{esc(s['quote_line_2'])}</span>"
        )
    return "\n    <div class=\"hero-quotes\" aria-hidden=\"true\">\n" + "\n".join(lines) + "\n    </div>\n    "


# ---------- about (definition + pull quote) ----------

def gen_definition(about):
    d = about["definition"]
    items = "\n".join(f"          <li>{esc(e)}</li>" for e in d["entries"])

    # Speaker button next to Pronunciation. Uses an uploaded audio file
    # when set; otherwise falls back to the browser's SpeechSynthesis
    # voice speaking 'speak_text'. The audio-lines SVG matches the
    # Lucide icon set so it stylistically fits the training badges.
    audio_src = (d.get("pronunciation_audio") or "").strip()
    speak_text = (d.get("speak_text") or d.get("word") or "").strip()
    speaker_svg = (
        '<svg viewBox="0 0 24 24" aria-hidden="true">'
        '<line x1="2" x2="2" y1="10" y2="14"/>'
        '<line x1="6" x2="6" y1="6" y2="18"/>'
        '<line x1="10" x2="10" y1="9" y2="15"/>'
        '<line x1="14" x2="14" y1="6" y2="18"/>'
        '<line x1="18" x2="18" y1="11" y2="13"/>'
        '<line x1="22" x2="22" y1="10" y2="14"/>'
        '</svg>'
    )
    speaker_btn = (
        '<button class="pron-play" type="button"'
        ' aria-label="Hear pronunciation"'
        f' data-audio="{esc(audio_src)}"'
        f' data-text="{esc(speak_text)}">'
        f'{speaker_svg}</button>'
    )

    return (
        "\n      <div class=\"def\">\n"
        f'        <h3>{esc(d["word"])} <small style="color:var(--muted);font-size:14px;font-weight:400">({esc(d["part_of_speech"])})</small></h3>\n'
        f'        <div class="pron">Pronunciation: {esc(d["pronunciation"])} {speaker_btn}</div>\n'
        "        <ol>\n"
        + items + "\n"
        "        </ol>\n"
        "      </div>\n      "
    )


def gen_pull_quote(about):
    """Pull-quote slider. Supports legacy single-object (pull_quote) and
    new list form (pull_quotes). With one item, renders static; with 2+,
    renders as a slider that JS rotates every 7s with a left-slide
    transition (see pullQuoteRotate in the main <script>)."""
    items = about.get("pull_quotes")
    if not items:
        single = about.get("pull_quote")
        items = [single] if single else []
    if not items:
        return "\n      <!-- no pull quotes configured -->\n      "

    multi = len(items) > 1
    slides_class = "pullquote-slides" + (" multi" if multi else " single")
    slide_html = []
    for i, q in enumerate(items):
        active = " active" if i == 0 else ""
        attribution = (q.get("attribution") or "").strip()
        cite_html = (
            f"\n            <cite>&mdash; {esc(attribution)}</cite>"
            if attribution else ""
        )
        slide_html.append(
            f'          <div class="pullquote-slide{active}">\n'
            f'            <p>{esc(q["text"])}</p>{cite_html}\n'
            f'          </div>'
        )
    return (
        "\n      <div class=\"pullquote\">\n"
        f'        <div class="{slides_class}">\n'
        + "\n".join(slide_html) + "\n"
        "        </div>\n"
        "      </div>\n      "
    )


# ---------- panels ----------

def gen_physical(p):
    items = [
        ("Age Range:", p["age_range"]),
        ("Height:", p["height"]),
        ("Eyes:", p["eyes"]),
        ("Hair:", p["hair"]),
        ("Tattoos:", p["tattoos"]),
        ("Piercings:", p["piercings"]),
    ]
    lis = "\n".join(
        f'          <li><span class="label">{esc(k)}</span> {esc(v)}</li>'
        for k, v in items
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Physical</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_languages(langs):
    lis = "\n".join(
        f'          <li><span class="label">{esc(l["name"])}</span><span class="sub">{esc(l["level"])}</span></li>'
        for l in langs
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Languages</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_languages_print(langs):
    parts = " &middot; ".join(f"{esc(l['name'])} ({esc(l['level'])})" for l in langs)
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Languages</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {parts}\n    </div>\n"
        "  </div>\n  "
    )


def gen_measurements(m):
    items = [
        ("Shoe:", m["shoe"]),
        ("Shirt:", m["shirt"]),
        ("Coat:", m["coat"]),
        ("Neck:", m["neck"]),
        ("Sleeve:", m["sleeve"]),
        ("Hat:", m["hat"]),
    ]
    lis = "\n".join(
        f'          <li><span class="label">{esc(k)}</span> {esc(v)}</li>'
        for k, v in items
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Measurements</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_licensing(lic):
    docs = "\n".join(f"          <li>{esc(d)}</li>" for d in lic["documents"])
    extras = (
        f'          <li><span class="label">Union:</span><span class="sub">{esc(lic["union"])}</span></li>\n'
        f'          <li><span class="label">Local Hire:</span><span class="sub">{esc(lic["local_hire"])}</span></li>'
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Licensing &amp; Hire</h4>\n"
        "        <ul>\n"
        + docs + "\n"
        + extras + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_licensing_print(lic):
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Licensing</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {' &middot; '.join(esc(d) for d in lic['documents'])}\n    </div>\n"
        "  </div>\n  "
    )


def gen_skills(skills_str):
    return (
        "\n      <div class=\"panel\">\n"
        "        <h4>Key Skills</h4>\n"
        f"        <p>\n          {esc(skills_str)}\n        </p>\n"
        "      </div>\n      "
    )


def gen_skills_print(skills_str):
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Special Skills</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {esc(skills_str)}\n    </div>\n"
        "  </div>\n  "
    )


def gen_favorite_films(films):
    lis = "\n".join(
        f'              <li>{esc(f["title"])} <span class="sub">{esc(f["director"])}, {esc(f["year"])}</span></li>'
        for f in films
    )
    return (
        "\n          <div class=\"panel\">\n"
        "            <h4>Favorite Films</h4>\n"
        "            <ul>\n"
        + lis + "\n"
        "            </ul>\n"
        "          </div>\n          "
    )


def gen_inspirations(insp):
    lis = "\n".join(f"              <li>{esc(n)}</li>" for n in insp)
    return (
        "\n          <div class=\"panel\">\n"
        "            <h4>Inspirations</h4>\n"
        "            <ul>\n"
        + lis + "\n"
        "            </ul>\n"
        "          </div>\n          "
    )


def gen_print_stats(panels):
    p = panels["physical"]
    m = panels["measurements"]
    cells = [
        ("Height", p["height"]),
        ("Eyes", p["eyes"]),
        ("Hair", p["hair"]),
        ("Age Range", p["age_range"]),
        ("Shoe", m["shoe"]),
        ("Suit", f"{m['coat']} / {m['shirt']} / {m['neck']}"),
    ]
    divs = "\n".join(
        f"    <div><strong>{esc(label)}</strong>{esc(value)}</div>"
        for label, value in cells
    )
    return (
        "\n  <div class=\"rs-stats\">\n"
        + divs + "\n"
        "  </div>\n  "
    )


# ---------- contact (email, socials, reel) ----------

# SVG icons for the supported social platforms.
SOCIAL_ICONS = {
    "Instagram": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2.2c3.2 0 3.6 0 4.8.1 1.2.1 1.8.2 2.2.4.6.2 1 .5 1.4.9.4.4.7.8.9 1.4.2.4.4 1 .4 2.2.1 1.2.1 1.6.1 4.8s0 3.6-.1 4.8c-.1 1.2-.2 1.8-.4 2.2-.2.6-.5 1-.9 1.4-.4.4-.8.7-1.4.9-.4.2-1 .4-2.2.4-1.2.1-1.6.1-4.8.1s-3.6 0-4.8-.1c-1.2-.1-1.8-.2-2.2-.4-.6-.2-1-.5-1.4-.9-.4-.4-.7-.8-.9-1.4-.2-.4-.4-1-.4-2.2C2.2 15.6 2.2 15.2 2.2 12s0-3.6.1-4.8c.1-1.2.2-1.8.4-2.2.2-.6.5-1 .9-1.4.4-.4.8-.7 1.4-.9.4-.2 1-.4 2.2-.4C8.4 2.2 8.8 2.2 12 2.2zm0 2c-3.1 0-3.5 0-4.7.1-1.1.1-1.6.2-1.9.3-.5.2-.8.4-1.1.7-.3.3-.5.6-.7 1.1-.1.3-.3.8-.3 1.9-.1 1.2-.1 1.6-.1 4.7s0 3.5.1 4.7c.1 1.1.2 1.6.3 1.9.2.5.4.8.7 1.1.3.3.6.5 1.1.7.3.1.8.3 1.9.3 1.2.1 1.6.1 4.7.1s3.5 0 4.7-.1c1.1-.1 1.6-.2 1.9-.3.5-.2.8-.4 1.1-.7.3-.3.5-.6.7-1.1.1-.3.3-.8.3-1.9.1-1.2.1-1.6.1-4.7s0-3.5-.1-4.7c-.1-1.1-.2-1.6-.3-1.9-.2-.5-.4-.8-.7-1.1-.3-.3-.6-.5-1.1-.7-.3-.1-.8-.3-1.9-.3-1.2-.1-1.6-.1-4.7-.1zm0 3.2a4.6 4.6 0 1 1 0 9.2 4.6 4.6 0 0 1 0-9.2zm0 1.9a2.7 2.7 0 1 0 0 5.4 2.7 2.7 0 0 0 0-5.4zm5.9-2.2a1.1 1.1 0 1 1 0 2.2 1.1 1.1 0 0 1 0-2.2z"/></svg>',
    "Letterboxd": '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="12" r="3.2"/><circle cx="12" cy="12" r="3.2" opacity=".6"/><circle cx="18" cy="12" r="3.2"/></svg>',
    "IMDb": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 6h20v12H2z" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="12" y="15" text-anchor="middle" font-size="7" font-weight="900" fill="currentColor" font-family="Montserrat">IMDb</text></svg>',
    "Actors Access": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 6h20v12H2z" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="12" y="15" text-anchor="middle" font-size="8" font-weight="900" fill="currentColor" font-family="Montserrat">AA</text></svg>',
    "Email": '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18v12H3z" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M3 7l9 6 9-6" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>',
}


def gen_socials(socials):
    items = []
    for s in socials:
        platform = s["platform"]
        url = s["url"]
        icon = SOCIAL_ICONS.get(platform, "")
        external = "" if url.startswith("mailto:") else ' target="_blank" rel="noopener"'
        items.append(
            f'          <a href="{esc(url)}"{external} aria-label="{esc(platform)}" title="{esc(platform)}">\n'
            f'            {icon}\n'
            f'          </a>'
        )
    return (
        "\n        <div class=\"socials\">\n"
        + "\n".join(items) + "\n"
        "        </div>\n        "
    )


def gen_reel(contact):
    r = contact["reel"]
    if r.get("url"):
        return (
            f'\n      <div class="reel">\n'
            f'        <iframe src="{esc(r["url"])}" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>\n'
            f'      </div>\n      '
        )
    if r.get("file"):
        return (
            f'\n      <div class="reel">\n'
            f'        <video controls preload="metadata"><source src="{esc(r["file"])}" type="video/mp4"></video>\n'
            f'      </div>\n      '
        )
    return (
        f'\n      <div class="reel">\n'
        f'        <span>{esc(r.get("placeholder", "Reel coming soon"))}</span>\n'
        f'      </div>\n      '
    )


def gen_contact_section(contact):
    cs = contact.get("contact_section", {})
    heading = cs.get("heading", "Let's Work")
    body = cs.get("body", "")
    email = contact["email"]
    return (
        '\n    <span class="kicker" style="font-family:\'Montserrat\',sans-serif;font-size:11px;color:var(--accent);letter-spacing:.3em;text-transform:uppercase">04 &mdash; Contact</span>\n'
        f'    <h2 style="margin-top:8px">{esc(heading)}</h2>\n'
        f'    <p style="color:var(--muted);max-width:520px;margin:14px auto 0">\n      {esc(body)}\n    </p>\n'
        f'    <a class="email" href="mailto:{esc(email)}">{esc(email)}</a>\n  '
    )


# ---------- site (SEO / OG / GA4) ----------

def gen_site_meta(site):
    s = site["seo"]
    return (
        f'\n<title>{esc(s["title"])}</title>\n'
        f'<meta name="description" content="{esc(s["description"])}">\n'
        f'<meta name="author" content="{esc(s["author"])}">\n'
        f'<meta name="theme-color" content="#2c2e3d">\n'
        f'<meta name="robots" content="{esc(s["robots"])}">\n'
        f'<link rel="canonical" href="{esc(s["canonical_url"])}">\n'
    )


def gen_og_tags(site):
    og = site["og"]
    tw = site["twitter"]
    canonical = site["seo"]["canonical_url"]
    return (
        f'\n<meta property="og:type" content="{esc(og["type"])}">\n'
        f'<meta property="og:site_name" content="{esc(og["site_name"])}">\n'
        f'<meta property="og:title" content="{esc(og["title"])}">\n'
        f'<meta property="og:description" content="{esc(og["description"])}">\n'
        f'<meta property="og:url" content="{esc(canonical)}">\n'
        f'<meta property="og:image" content="{esc(og["image"])}">\n'
        f'<meta property="og:image:secure_url" content="{esc(og["image"])}">\n'
        f'<meta property="og:image:width" content="1200">\n'
        f'<meta property="og:image:height" content="630">\n'
        f'<meta property="og:image:alt" content="{esc(og["image_alt"])}">\n'
        f'<meta property="og:locale" content="{esc(og["locale"])}">\n'
        f'<meta property="profile:first_name" content="Frank">\n'
        f'<meta property="profile:last_name" content="Rizzo">\n'
        f'<meta property="profile:gender" content="male">\n'
        '\n<!-- Twitter / X -->\n'
        f'<meta name="twitter:card" content="{esc(tw["card"])}">\n'
        f'<meta name="twitter:title" content="{esc(og["title"])}">\n'
        f'<meta name="twitter:description" content="{esc(og["description"])}">\n'
        f'<meta name="twitter:image" content="{esc(og["image"])}">\n'
        f'<meta name="twitter:image:alt" content="{esc(og["image_alt"])}">\n'
    )


def gen_ga4(site):
    ga4 = site["analytics"]["ga4_id"]
    return (
        f'\n<script async src="https://www.googletagmanager.com/gtag/js?id={esc(ga4)}"></script>\n'
        '<script>\n'
        '  window.dataLayer = window.dataLayer || [];\n'
        '  function gtag(){dataLayer.push(arguments);}\n'
        "  gtag('js', new Date());\n"
        f"  gtag('config', '{esc(ga4)}', {{ 'anonymize_ip': true }});\n"
        '</script>\n'
    )


def gen_menu(site):
    items = site.get("menu", [])
    if not items:
        return "\n  <nav class=\"nav\"></nav>\n  "
    links = "\n".join(
        f'    <a href="{esc(m["url"])}">{esc(m["label"])}</a>'
        for m in items
    )
    return "\n  <nav class=\"nav\">\n" + links + "\n  </nav>\n  "


# Map of section toggle key → CSS selector to hide when false.
# When you add a new toggleable section, drop the (key, selector)
# pair here AND expose the toggle in admin/config.yml > Sections.
SECTION_SELECTORS = {
    "about":           "#about",
    "profile_bio":     ".profile-bio",
    "profile_gallery": ".headshot-gallery",
    "profile_socials": ".socials",
    "resume":          "#resume",
    "credits":         "#credits",
    "reel":            "#reel-wrapper",
    "contact":         "#contact",
}


def gen_section_visibility(site):
    """Emit a <style> block with display:none rules for any section
    toggled off in site.yml. Renders in <head> so it applies before
    body paints - zero flicker."""
    sections = site.get("sections") or {}
    hidden_rules = []
    for key, selector in SECTION_SELECTORS.items():
        if sections.get(key, True) is False:
            hidden_rules.append(f"{selector}{{display:none!important}}")
    if not hidden_rules:
        return "\n<!-- all sections visible -->\n"
    return "\n<style>" + "".join(hidden_rules) + "</style>\n"


def gen_footer(site):
    f = site.get("footer", {})
    template = f.get("text", "© {{year}} Rizzo.cc")
    show_version = f.get("show_version", True)

    # Replace {{year}} with the dynamic year span (filled by JS at runtime)
    rendered = esc(template).replace("{{year}}", '<span id="yr"></span>')

    # Append version chip if enabled (replaces {{version}} if present, else
    # appends as the next visible element)
    if show_version:
        version_html = f'<span class="ver">{esc(SITE_VERSION)}</span>'
        if "{{version}}" in rendered:
            rendered = rendered.replace("{{version}}", version_html)
        else:
            rendered = rendered.rstrip() + " " + version_html
    else:
        rendered = rendered.replace("{{version}}", "")

    return f"\n<footer>\n  {rendered}\n</footer>\n"


# ---------- main ----------

def _load_list(path):
    """Load a YAML file shaped like `entries: [...]` and return that list.
    Returns [] if the file is missing or empty."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("entries", []) or []


def _load_obj(path):
    """Load a YAML file and return its top-level dict.
    Returns {} if the file is missing or empty."""
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main():
    # Each collection's data is split across multiple per-topic files so
    # Decap's sidebar lists Film / TV / Theater / Physical / Skills / Menu
    # / Footer / etc. as separate clickable entries instead of one giant
    # blob. The dicts here re-assemble the old shapes so the gen_*
    # functions don't need to change.

    # ---- Credits ----------------------------------------------------
    tabs_doc = _load_obj(DATA / "credits-tabs.yml")
    theater_footnotes_doc = _load_obj(DATA / "theater-footnotes.yml")
    credits = {
        "film": _load_list(DATA / "film.yml"),
        "tv": _load_list(DATA / "tv.yml"),
        "theater": _load_list(DATA / "theater.yml"),
        "commercial": _load_list(DATA / "commercial.yml"),
        "tab_visibility": tabs_doc.get("tabs") or {},
        "theater_footnotes": theater_footnotes_doc,
    }

    # ---- Stats / Skills / Influences -------------------------------
    panels = {
        "physical":       _load_obj(DATA / "physical.yml"),
        "measurements":   _load_obj(DATA / "measurements.yml"),
        "languages":      _load_list(DATA / "languages.yml"),
        "licensing":      _load_obj(DATA / "licensing.yml"),
        "skills":         _load_obj(DATA / "skills.yml").get("text", ""),
        "favorite_films": _load_list(DATA / "favorite-films.yml"),
        "inspirations":   _load_list(DATA / "inspirations.yml"),
    }

    # ---- Contact / Socials / Reel ----------------------------------
    contact = {
        **_load_obj(DATA / "contact.yml"),         # email + contact_section
        "socials": _load_list(DATA / "socials.yml"),
        "reel":    _load_obj(DATA / "reel.yml"),
    }

    # ---- Site Settings ---------------------------------------------
    seo_doc = _load_obj(DATA / "seo.yml")
    site = {
        "seo":       seo_doc.get("seo", {}),
        "og":        seo_doc.get("og", {}),
        "twitter":   seo_doc.get("twitter", {}),
        "favicon":   _load_obj(DATA / "favicon.yml"),
        "analytics": _load_obj(DATA / "analytics.yml"),
        "menu":      _load_list(DATA / "menu.yml"),
        "footer":    _load_obj(DATA / "footer.yml"),
        "sections":  _load_obj(DATA / "sections.yml"),
    }

    # ---- Other single-file inputs ----------------------------------
    training = yaml.safe_load((DATA / "training.yml").read_text(encoding="utf-8"))
    hero = yaml.safe_load((DATA / "hero.yml").read_text(encoding="utf-8"))
    about = yaml.safe_load((DATA / "about.yml").read_text(encoding="utf-8"))
    html = INDEX.read_text(encoding="utf-8")

    # Head: SEO meta, OG, GA4
    html = replace_block(html, "site-meta", gen_site_meta(site))
    html = replace_block(html, "og-tags", gen_og_tags(site))
    html = replace_block(html, "ga4", gen_ga4(site))

    # Chrome: top-nav menu + footer + section visibility
    html = replace_block(html, "menu", gen_menu(site))
    html = replace_block(html, "footer", gen_footer(site))
    html = replace_block(html, "section-visibility", gen_section_visibility(site))

    # Bio + Credits + Training
    html = replace_block(html, "bio", gen_bio())
    html = replace_block(html, "training", gen_training_screen(training))
    html = replace_block(html, "print-training", gen_training_print(training))
    # Tabs strip — only includes visible tabs; first visible gets active state
    html = replace_block(html, "credits-tabs", gen_credits_tabs(credits))

    # Per-tab panels: render only when the tab is visible. The build script's
    # replace_block fills with empty content so the panel <div> disappears.
    def panel_or_hidden(slug, gen, *args):
        visible_slugs = {s for s, _ in _visible_tabs(credits)}
        if slug not in visible_slugs:
            return "\n    "
        return gen(*args, is_active=_is_first_visible(credits, slug))

    html = replace_block(html, "film-credits",
                         panel_or_hidden("film", gen_film_screen, credits["film"]))
    html = replace_block(html, "tv-credits",
                         panel_or_hidden("tv", gen_tv_screen, credits["tv"]))
    html = replace_block(html, "theater-credits",
                         panel_or_hidden("theater", gen_theater_screen, credits["theater"], credits["theater_footnotes"]))
    html = replace_block(html, "commercial-credits",
                         panel_or_hidden("commercial", gen_commercial_screen, credits.get("commercial", [])))

    # Printed PDF resume always uses all sections except Commercial
    # (Commercial is intentionally omitted from print).
    html = replace_block(html, "print-film-credits", gen_film_print(credits["film"]))
    html = replace_block(html, "print-tv-credits", gen_tv_print(credits["tv"]))
    html = replace_block(html, "print-theater-credits", gen_theater_print(credits["theater"], credits["theater_footnotes"]))

    # Hero
    html = replace_block(html, "hero-slides", gen_hero_slides(hero))
    html = replace_block(html, "hero-quotes", gen_hero_quotes(hero))

    # About
    html = replace_block(html, "rizzo-definition", gen_definition(about))
    html = replace_block(html, "pull-quote", gen_pull_quote(about))

    # Resume panels
    html = replace_block(html, "physical", gen_physical(panels["physical"]))
    html = replace_block(html, "languages", gen_languages(panels["languages"]))
    html = replace_block(html, "print-languages", gen_languages_print(panels["languages"]))
    html = replace_block(html, "measurements", gen_measurements(panels["measurements"]))
    html = replace_block(html, "licensing", gen_licensing(panels["licensing"]))
    html = replace_block(html, "print-licensing", gen_licensing_print(panels["licensing"]))
    html = replace_block(html, "skills", gen_skills(panels["skills"]))
    html = replace_block(html, "print-skills", gen_skills_print(panels["skills"]))
    html = replace_block(html, "favorite-films", gen_favorite_films(panels["favorite_films"]))
    html = replace_block(html, "inspirations", gen_inspirations(panels["inspirations"]))
    html = replace_block(html, "print-stats", gen_print_stats(panels))

    # Contact / socials / reel
    html = replace_block(html, "socials", gen_socials(contact["socials"]))
    html = replace_block(html, "reel", gen_reel(contact))
    html = replace_block(html, "contact-section", gen_contact_section(contact))

    INDEX.write_text(html, encoding="utf-8")
    print(f"Wrote {INDEX.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
