"""
build-content.py — Regenerate content sections of index.html from
the structured files in data/. Run from the acting/ root:

    python .scripts/build-content.py

Inputs (split across per-topic files so the Decap sidebar lists each
as a separate clickable entry):
  data/bio.md             — bio paragraph (with optional front-matter)
  data/hero.yml           — hero slideshow (paired image + 2-line quote per slide)
  data/about.yml          — RIZZO definition + pronunciation audio + pull quotes
  data/headshots.yml      — profile photo + gallery thumbnails (entries:)
  data/training.yml       — training entries

  Credits collection:
    data/film.yml         — film credits     (entries:)
    data/tv.yml           — tv credits       (entries:)
    data/theater.yml      — theater credits  (entries:)
    data/commercial.yml   — commercial credits (entries:)
    data/credits-tabs.yml — credit tab show/hide toggles (tabs:)

  Stats / Skills / Influences collection:
    data/physical.yml       — appearance (age, height, eyes, hair, ...)
    data/measurements.yml   — wardrobe sizes
    data/languages.yml      — spoken languages (entries:)
    data/licensing.yml      — documents + union + local_hire
    data/skills.yml         — Key Skills paragraph (text:)
    data/favorite-films.yml — favorite films (entries:)
    data/inspirations.yml   — directors/creators that inform work (entries:)

  Contact, Socials, Reel collection:
    data/contact.yml      — email + contact_section copy
    data/socials.yml      — social pills (entries:)
    data/reel.yml         — reel embed (url, file, placeholder)

  Site Settings collection:
    data/seo.yml          — SEO + Open Graph + Twitter card
    data/favicon.yml      — favicon source image
    data/analytics.yml    — GA4 measurement ID
    data/menu.yml         — top-nav items (entries:)
    data/footer.yml       — footer text + show_version
    data/sections.yml     — section show/hide toggles (about/profile_bio/...)

Updates these EDIT-marked blocks in index.html (and only these):
  EDIT: bio                   ← from data/bio.md
  EDIT: training              ← from data/training.yml
  EDIT: print-training        ← from data/training.yml
  EDIT: film-credits          ← from data/film.yml
  EDIT: print-film-credits    ← from data/film.yml
  EDIT: tv-credits            ← from data/tv.yml
  EDIT: print-tv-credits      ← from data/tv.yml
  EDIT: theater-credits       ← from data/theater.yml
  EDIT: print-theater-credits ← from data/theater.yml
  EDIT: commercial-credits    ← from data/commercial.yml
  EDIT: credits-tabs          ← from data/credits-tabs.yml (tabs)
  EDIT: hero-slides           ← from data/hero.yml
  EDIT: hero-quotes           ← from data/hero.yml
  EDIT: headshot-main         ← from data/headshots.yml (first entry)
  EDIT: headshot-gallery      ← from data/headshots.yml (all entries)
  EDIT: rizzo-definition      ← from data/about.yml
  EDIT: pull-quote            ← from data/about.yml
  EDIT: physical              ← from data/physical.yml
  EDIT: languages             ← from data/languages.yml
  EDIT: print-languages       ← from data/languages.yml
  EDIT: measurements          ← from data/measurements.yml
  EDIT: licensing             ← from data/licensing.yml
  EDIT: print-licensing       ← from data/licensing.yml
  EDIT: skills                ← from data/skills.yml
  EDIT: print-skills          ← from data/skills.yml
  EDIT: favorite-films        ← from data/favorite-films.yml
  EDIT: inspirations          ← from data/inspirations.yml
  EDIT: print-stats           ← from data/physical.yml + data/measurements.yml
  EDIT: socials               ← from data/socials.yml
  EDIT: reel                  ← from data/reel.yml
  EDIT: contact-section       ← from data/contact.yml (contact_section)
  EDIT: site-meta             ← from data/seo.yml (SEO subtree)
  EDIT: og-tags               ← from data/seo.yml (OG + Twitter)
  EDIT: ga4                   ← from data/analytics.yml
  EDIT: menu                  ← from data/menu.yml
  EDIT: footer                ← from data/footer.yml
  EDIT: section-visibility    ← from data/sections.yml (emits CSS rules to hide off sections)

NOTE: the JSON-LD Movie nodes in index.html are NOT regenerated by this
script (they cross-reference Person via @id which would tangle the
generation). When you add or remove a film credit, also update the
Movie nodes inside the EDIT: json-ld block manually — see EDITING.md.

Idempotent: running with unchanged data files produces unchanged output.
"""
from pathlib import Path
import re
import html as html_lib
import urllib.parse
import datetime as _dt

try:
    import yaml
except ImportError:
    print("Install PyYAML first:  pip install PyYAML")
    raise SystemExit(1)

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
DATA = ROOT / "data"

# Single source of truth for the version chip displayed in the footer.
# Bump this when you release a new version of the site (and add the
# matching ### v0.X.Y entry to README.md changelog).
SITE_VERSION = "v0.10.1"


# ---------- helpers ----------

def esc(s):
    """HTML-escape a value safely. Returns empty string for None."""
    if s is None:
        return ""
    return html_lib.escape(str(s), quote=False)


def md_inline(s):
    """Tiny markdown subset for the bio: **bold** and *italic*."""
    s = esc(s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
    s = re.sub(r"\*(.+?)\*", r"<em>\1</em>", s)
    return s


def replace_block(html, marker, new_inner):
    """Replace content between <!-- EDIT: marker [...] --> and
    <!-- /EDIT: marker -->. The marker comments themselves are preserved.
    The EDIT comment may span multiple lines and contain `>` chars in
    its description, so the opening-comment match uses .*? rather than
    [^>]* and the whole pattern runs with DOTALL."""
    pattern = re.compile(
        r"(<!--\s*EDIT:\s*" + re.escape(marker) + r"\b.*?-->)"
        r"(.*?)"
        r"(<!--\s*/EDIT:\s*" + re.escape(marker) + r"\s*-->)",
        re.DOTALL,
    )
    if not pattern.search(html):
        raise SystemExit(f"Marker not found in index.html: EDIT: {marker}")
    return pattern.sub(
        lambda m: m.group(1) + new_inner + m.group(3),
        html,
        count=1,
    )


# ---------- generators ----------

def load_bio_body():
    text = (DATA / "bio.md").read_text(encoding="utf-8")
    # Strip front-matter if present
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            text = parts[2]
    return text.strip()


def gen_bio():
    body = load_bio_body()
    return (
        "\n"
        '        <p class="profile-bio">\n'
        "          " + md_inline(body).replace("\n", "\n          ") + "\n"
        "        </p>\n"
        "        "
    )


# Lucide-style line-icon SVG paths (24x24 viewBox). One per training "kind"
# value. The badge CSS strokes them with currentColor and sets width/height,
# so these paths only need d-data. Keep the keys aligned with the Decap
# select options in admin/config.yml > training > kind > options.
TRAINING_ICONS = {
    "Workshop":     '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94"/>',
    "Class":        '<path d="M2 3h6a4 4 0 0 1 4 4v13a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v13a3 3 0 0 1 3-3h7z"/>',
    "Course":       '<path d="M2 3h6a4 4 0 0 1 4 4v13a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v13a3 3 0 0 1 3-3h7z"/>',
    "Intensive":    '<path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0"/>',
    "Masterclass":  '<circle cx="12" cy="9" r="6"/><path d="M15.5 13.5 17 22l-5-3-5 3 1.5-8.5"/>',
    "Conservatory": '<path d="M3 21h18M5 21V8l7-4 7 4v13M9 9v4M12 9v4M15 9v4M9 17v4M15 17v4"/>',
    "Showcase":     '<path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="22"/>',
    "Revue":        '<circle cx="9" cy="11" r="5"/><circle cx="15" cy="13" r="5"/>',
    "Coaching":     '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="m16 11 2 2 4-4"/>',
}


# ---------- printed resume: one-page density enforcement ----------
#
# HARD RULE: the printed PDF resume is always ONE letter page.
#
# Rather than hoping hand-tuned margins keep holding as credits get added,
# the build estimates the sheet's rendered height and picks the least
# aggressive density tier that still fits. Each tier spends a specific
# space-saving lever:
#
#   Tier 1  baseline — today's comfortable layout, nothing spent
#   Tier 2  tighter leading, row padding, and section headings
#   Tier 3  Tier 2 + drop the footer rizzo.cc/email block and move the
#           QR code up beside the headshot (free — the header row is
#           already 1.5in tall for the headshot, so the QR rides along)
#   Tier 4  Tier 3 + step every font down
#
# The estimate is a heuristic over row counts and wrap math, not a real
# measurement — a credit with a long sketch list costs more than a short
# one, which is modelled, but font metrics are approximated. Thresholds
# are therefore deliberately conservative. If content ever exceeds even
# Tier 4, the build prints a loud warning rather than silently shipping
# a two-page resume.
#
# Letter portrait is 11in tall; @page margin is 0.3in top and bottom,
# leaving 10.4in of printable height. 1in = 72pt.
PRINT_BUDGET_PT = 10.4 * 72       # 748.8pt

# Slack held back from the budget so a tier is only chosen if it fits with
# room to spare. The estimator approximates font metrics, so this absorbs
# the error rather than padding every constant below (which would make the
# model itself wrong and harder to reason about). 24pt = 1/3 inch.
PRINT_SAFETY_PT = 24.0

# Per-element height estimates in points, computed from the @media print
# CSS (font-size x line-height + padding + borders + margins, at 1px =
# 0.75pt). Calibrated against a real generated PDF: these produce ~669pt
# for the tier-1 content as of v0.8.1, matching the measured sheet.
# Recalibrate if the print typography changes.
_PT = {
    "header":         115.0,   # 1.5in headshot (108) + padding/border/margin
    "stats":           30.0,   # 6-col grid, label+value, + border + margin
    "section_chrome":  21.0,   # h2 (11) + underline + section margin-bottom
    "table_row":       12.6,   # 8.5pt x 1.22 + 1.5px padding top/bottom
    "row_wrap":         9.8,   # each ADDITIONAL wrapped line (8-8.5pt mix)
    "theater_foot":    13.0,   # the asterisk footnote under the theater table
    "training_row":    21.0,   # title line (10.4) + sub line (9) + margin
    "training_wrap":    9.0,   # each additional wrapped line in a training sub
    "text_line":       10.0,   # one line of a Languages/Skills/Licensing blob
    "footer":          65.0,   # QR 0.7in (50.4) + label + border + margin
}

# Approximate characters per line for each column, derived from the
# column widths in the print CSS against a 7.9in content width.
_CPL = {
    "title":      43,   # td.t  32% @ 8.5pt bold
    "role":       60,   # td.r  38% @ 8.5pt
    "role_thin":  64,   # td.r  38% @ 8pt (theater uses the smaller size)
    "detail":     45,   # td.d  30% @ 8.5pt italic
    "train_ttl":  60,   # training entry title, 2-column @ 8.5pt bold
    "train_sub":  74,   # training entry sub-line, 2-column @ 7.5pt
    "blob":      155,   # full-width Languages / Skills / Licensing @ 8pt
}


def _lines(text, chars_per_line):
    """How many rendered lines a string needs at a given wrap width."""
    n = len(str(text or ""))
    if n == 0:
        return 1
    return max(1, -(-n // chars_per_line))     # ceil division


def _table_block_pt(rows, cols, scale=1.0):
    """Height of one credit table's rows. `cols` maps each row dict key to
    its chars-per-line budget; a row is as tall as its tallest cell."""
    total = 0.0
    for r in rows:
        tallest = 1
        for key, cpl in cols.items():
            tallest = max(tallest, _lines(r.get(key, ""), cpl))
        total += _PT["table_row"] * scale
        total += _PT["row_wrap"] * scale * (tallest - 1)
    return total


def estimate_print_height_pt(credits, training, panels, tier):
    """Estimated rendered height of the printed sheet, in points, for a
    given density tier. Tier effects mirror what the .rs-d{n} CSS does."""
    # Tier multipliers: (variable content scale, section chrome scale,
    #                    header scale, footer included?)
    variable, chrome, header, footer_on = {
        1: (1.00, 1.00, 1.00, True),
        2: (0.93, 0.85, 1.00, True),
        3: (0.93, 0.85, 1.00, False),
        4: (0.84, 0.78, 0.92, False),
    }[tier]

    total = _PT["header"] * header + _PT["stats"] * variable

    sections = 0

    film = credits.get("film") or []
    if film:
        sections += 1
        total += _table_block_pt(
            film,
            {"title": _CPL["title"], "role": _CPL["role"], "director": _CPL["detail"]},
            variable,
        )

    tv = credits.get("tv") or []
    if tv:
        sections += 1
        total += _table_block_pt(
            tv,
            {"title": _CPL["title"], "role": _CPL["role"], "network": _CPL["detail"]},
            variable,
        )

    theater = credits.get("theater") or []
    if theater:
        sections += 1
        total += _table_block_pt(
            theater,
            {"production": _CPL["title"], "role": _CPL["role_thin"], "venue": _CPL["detail"]},
            variable,
        )
        # Footnote line renders only when a marker is actually in use.
        _, active_notes = _theater_resolve(theater, credits.get("theater_footnotes") or {})
        if active_notes:
            total += _PT["theater_foot"] * variable

    entries = (training or {}).get("entries") or []
    if entries:
        sections += 1
        # Two columns, so the section is only as tall as the taller column.
        per_entry = []
        for e in entries:
            sub = " · ".join(p for p in (e.get("teachers"), e.get("school")) if p)
            h = _PT["training_row"] * variable
            h += _PT["training_wrap"] * variable * (_lines(sub, _CPL["train_sub"]) - 1)
            h += _PT["training_wrap"] * variable * (_lines(e.get("title"), _CPL["train_ttl"]) - 1)
            per_entry.append(h)
        # CSS multi-column fills column 1 then column 2, balancing by
        # height. Simulate that greedily (tallest-first into whichever
        # column is currently shorter) and take the taller column — a flat
        # total/2 under-counts, and total/2 + max/2 over-counts.
        col_a = col_b = 0.0
        for h in sorted(per_entry, reverse=True):
            if col_a <= col_b:
                col_a += h
            else:
                col_b += h
        total += max(col_a, col_b)

    # Full-width text blobs
    langs = panels.get("languages") or []
    if langs:
        sections += 1
        blob = " · ".join(f'{l.get("name","")} ({l.get("level","")})' for l in langs)
        total += _PT["text_line"] * variable * _lines(blob, _CPL["blob"])

    skills = panels.get("skills") or ""
    if skills:
        sections += 1
        total += _PT["text_line"] * variable * _lines(skills, _CPL["blob"])

    lic = panels.get("licensing") or {}
    lic_parts = list(lic.get("documents") or [])
    if lic.get("union"):
        lic_parts.append(lic["union"])
    if lic.get("local_hire"):
        lic_parts.append(f'Local Hire: {lic["local_hire"]}')
    if lic_parts:
        sections += 1
        total += _PT["text_line"] * variable * _lines(" · ".join(lic_parts), _CPL["blob"])

    total += _PT["section_chrome"] * chrome * sections

    if footer_on:
        total += _PT["footer"]

    return total


def resolve_print_density(credits, training, panels, print_cfg):
    """Pick the least aggressive density tier that fits on one page.
    An explicit tier in print-resume.yml overrides the automatic choice.
    Returns (tier, estimate_pt, was_forced)."""
    mode = str((print_cfg or {}).get("density_mode", "auto")).strip().lower()

    if mode in {"1", "2", "3", "4"}:
        tier = int(mode)
        return tier, estimate_print_height_pt(credits, training, panels, tier), True

    usable = PRINT_BUDGET_PT - PRINT_SAFETY_PT
    for tier in (1, 2, 3, 4):
        est = estimate_print_height_pt(credits, training, panels, tier)
        if est <= usable:
            return tier, est, False

    # Nothing fits — return the tightest tier and let main() warn loudly.
    return 4, estimate_print_height_pt(credits, training, panels, 4), False


def apply_print_density_class(html, tier):
    """Stamp rs-d{tier} onto the .resume-sheet root so the tier CSS
    applies. Replaces any previously stamped tier."""
    def _sub(m):
        classes = [c for c in m.group(1).split() if not c.startswith("rs-d")]
        classes.append(f"rs-d{tier}")
        return f'<div class="{" ".join(classes)}"'
    return re.sub(
        r'<div class="(resume-sheet[^"]*)"',
        _sub,
        html,
        count=1,
    )


def gen_headshot_main(headshots):
    """The large 280x280 headshot. Uses the FIRST entry in headshots.yml
    as the default; the gallery JS swaps its src on thumbnail clicks."""
    entries = headshots.get("entries") or []
    if not entries:
        # No headshots configured — fall back to the legacy single file so
        # the profile block never renders a broken image.
        src, alt = "assets/headshot.jpg", "Headshot"
    else:
        src = entries[0].get("image", "assets/headshot.jpg")
        alt = entries[0].get("alt", "Headshot")
    return (
        "\n      <img class=\"headshot\"\n"
        f'           src="{esc(src)}"\n'
        f'           alt="{esc(alt)}"\n'
        '           width="280" height="280"\n'
        '           fetchpriority="high"\n'
        '           decoding="async">\n      '
    )


def gen_headshot_gallery(headshots):
    """65px thumbnail row. Each button carries data-src, which the gallery
    JS swaps into the main headshot. First entry starts active."""
    entries = headshots.get("entries") or []
    if not entries:
        return "\n        "
    buttons = []
    for i, e in enumerate(entries):
        src = e.get("image", "")
        if not src:
            continue
        label = e.get("label") or f"Headshot {i + 1}"
        active = ' class="active"' if i == 0 else ""
        buttons.append(
            f'          <button type="button"{active} data-src="{esc(src)}" '
            f'aria-label="{esc(label)}">\n'
            f'            <img src="{esc(src)}" alt="{esc(label)}" loading="lazy">\n'
            f'          </button>'
        )
    if not buttons:
        return "\n        "
    return (
        '\n        <div class="headshot-gallery" aria-label="Headshot gallery">\n'
        + "\n".join(buttons)
        + "\n        </div>\n        "
    )


def kind_badge(kind, leading_space=False):
    """Render a training kind/badge <span> with its matching line icon.
    Returns '' when kind is empty. leading_space=True prepends a space so the
    badge sits cleanly after another inline element (used in the print path)."""
    kind = (kind or "").strip()
    if not kind:
        return ""
    icon = TRAINING_ICONS.get(kind, "")
    svg = f'<svg viewBox="0 0 24 24" aria-hidden="true">{icon}</svg>' if icon else ""
    lead = " " if leading_space else ""
    return f'{lead}<span class="kind">{svg}{esc(kind)}</span>'


def gen_training_screen(training):
    lines = []
    for e in training["entries"]:
        sub_parts = [p for p in (e.get("teachers", ""), e.get("school", "")) if p]
        sub = " &middot; ".join(esc(p) for p in sub_parts)
        kind_html = kind_badge(e.get("kind"))
        lines.append(
            '          <li><span class="label">'
            + esc(e["title"])
            + '</span>'
            + kind_html
            + '<span class="sub">'
            + sub
            + "</span></li>"
        )
    return (
        "\n      <div class=\"panel col-6\">\n"
        "        <h4>Education / Training</h4>\n"
        "        <ul>\n"
        + "\n".join(lines)
        + "\n        </ul>\n"
        "      </div>\n      "
    )


def gen_training_print(training):
    lines = []
    for e in training["entries"]:
        sub_parts = [p for p in (e.get("teachers", ""), e.get("school", "")) if p]
        sub = " &middot; ".join(esc(p) for p in sub_parts)
        kind_html = kind_badge(e.get("kind"), leading_space=True)
        lines.append(
            f"      <div><strong>{esc(e['title'])}{kind_html}</strong><em>{sub}</em></div>"
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Training</h2>\n"
        "    <div class=\"rs-training-list\">\n"
        + "\n".join(lines)
        + "\n    </div>\n"
        "  </div>\n  "
    )


# Order of the credit tabs (slug → display label). The tabs strip is
# rendered in this order; the first tab whose visibility is true gets
# the active state. Hidden tabs are omitted from both the strip and
# the panel area below.
TAB_ORDER = [
    ("film",       "Film"),
    ("tv",         "TV"),
    ("theater",    "Theater"),
    ("commercial", "Commercial"),
]


def _visible_tabs(credits):
    vis = credits.get("tab_visibility") or {}
    # Default to visible if a flag is omitted from credits.yml; commercial
    # defaults to hidden (placeholder until real entries exist).
    defaults = {"film": True, "tv": True, "theater": True, "commercial": False}
    return [
        (slug, label)
        for slug, label in TAB_ORDER
        if vis.get(slug, defaults.get(slug, True))
    ]


def _is_first_visible(credits, slug):
    vt = _visible_tabs(credits)
    return bool(vt) and vt[0][0] == slug


def gen_credits_tabs(credits):
    visible = _visible_tabs(credits)
    if not visible:
        return "\n    <div class=\"tabs\" role=\"tablist\"></div>\n    "
    buttons = []
    for i, (slug, label) in enumerate(visible):
        active = " active" if i == 0 else ""
        buttons.append(
            f'      <button class="tab{active}" data-tab="{esc(slug)}" role="tab">{esc(label)}</button>'
        )
    # The .pill is the sliding cyan background behind the active tab.
    # JS sets its transform + width to track the active button.
    return (
        "\n    <div class=\"tabs\" role=\"tablist\">\n"
        "      <span class=\"pill\" aria-hidden=\"true\"></span>\n"
        + "\n".join(buttons)
        + "\n    </div>\n    "
    )


def gen_film_screen(films, is_active=True):
    cls = "tab-panel active" if is_active else "tab-panel"
    rows = []
    for f in films:
        title = esc(f["title"])
        href = (
            f"https://www.imdb.com/title/{esc(f['imdb'])}/"
            if f.get("imdb")
            else f"https://www.imdb.com/find/?s=tt&q={title.replace(' ', '+')}"
        )
        rows.append(
            f'          <tr><td class="title"><a href="{href}" target="_blank" rel="noopener" title="View on IMDB">{title}</a> '
            f'<span class="sub" style="color:var(--dim)">({esc(f["type"])}, {esc(f["year"])})</span></td>'
            f'<td class="role">{esc(f["role"])}</td>'
            f'<td class="dir">dir. {esc(f["director"])}</td></tr>'
        )
    return (
        f'\n    <div class="{cls}" id="film">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Director</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_film_print(films):
    rows = []
    for f in films:
        rows.append(
            f'      <tr><td class="t">{esc(f["title"])} '
            f'<em style="color:#888;font-style:normal">({esc(f["type"])}, {esc(f["year"])})</em></td>'
            f'<td class="r">{esc(f["role"])}</td>'
            f'<td class="d">dir. {esc(f["director"])}</td></tr>'
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Film</h2>\n"
        "    <table class=\"rs-table\">\n"
        + "\n".join(rows)
        + "\n    </table>\n"
        "  </div>\n  "
    )


def gen_tv_screen(tv, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    rows = []
    for t in tv:
        rows.append(
            f'          <tr><td class="title">{esc(t["title"])} '
            f'<span class="sub" style="color:var(--dim)">({esc(t["season"])})</span></td>'
            f'<td class="role">{esc(t["role"])}</td>'
            f'<td class="dir">{esc(t["network"])}</td></tr>'
        )
    return (
        f'\n    <div class="{cls}" id="tv">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Network</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_tv_print(tv):
    rows = []
    for t in tv:
        rows.append(
            f'      <tr><td class="t">{esc(t["title"])} '
            f'<em style="color:#888;font-style:normal">({esc(t["season"])})</em></td>'
            f'<td class="r">{esc(t["role"])}</td>'
            f'<td class="d">{esc(t["network"])}</td></tr>'
        )
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Television</h2>\n"
        "    <table class=\"rs-table\">\n"
        + "\n".join(rows)
        + "\n    </table>\n"
        "  </div>\n  "
    )


def _theater_resolve(theater, footnotes_doc):
    """Returns (rows, active_footnotes) where each row is a dict of resolved
    cell values, and active_footnotes is the list of {marker, long} pairs
    whose marker appears on at least one entry."""
    strict = bool(footnotes_doc.get("strict_mode", False))
    notes = footnotes_doc.get("footnotes") or []
    by_marker = {(n.get("marker") or ""): n for n in notes}

    rows = []
    used_markers = []
    for t in theater:
        marker = (t.get("footnote") or "").strip()
        if strict and marker and marker in by_marker:
            # Strict Mode: swap venue for the footnote's short form
            venue_text = by_marker[marker].get("short") or t["venue"]
            venue_marker = ""
        else:
            venue_text = t["venue"]
            venue_marker = marker if marker in by_marker else ""
        if venue_marker and venue_marker not in used_markers:
            used_markers.append(venue_marker)
        rows.append({
            "production": t["production"],
            "role": t["role"],
            "venue": venue_text,
            "marker": venue_marker,
        })

    active_footnotes = [] if strict else [
        {"marker": m, "long": by_marker[m].get("long", "")} for m in used_markers
    ]
    return rows, active_footnotes


def gen_theater_screen(theater, footnotes_doc, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    resolved, active_footnotes = _theater_resolve(theater, footnotes_doc)
    rows = []
    for t in resolved:
        role_cell = (
            f'Sketches: <span style="color:var(--muted);font-weight:400">{esc(t["role"])}</span>'
            if "," in t["role"]
            else esc(t["role"])
        )
        marker_html = (
            f'<sup class="venue-mark">{esc(t["marker"])}</sup>'
            if t["marker"] else ""
        )
        rows.append(
            f'          <tr><td class="title">{esc(t["production"])}</td>'
            f'<td class="role">{role_cell}</td>'
            f'<td class="dir">{esc(t["venue"])}{marker_html}</td></tr>'
        )
    foot_html = ""
    if active_footnotes:
        items = "\n".join(
            f'        <li><span class="m">{esc(n["marker"])}</span> {esc(n["long"])}</li>'
            for n in active_footnotes
        )
        foot_html = (
            '\n      <ul class="theater-footnotes">\n'
            + items
            + "\n      </ul>"
        )
    return (
        f'\n    <div class="{cls}" id="theater">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Production</th><th>Role / Sketches</th><th>Stage</th></tr></thead>\n"
        "        <tbody>\n"
        + "\n".join(rows)
        + "\n        </tbody>\n"
        "      </table>"
        + foot_html
        + "\n    </div>\n    "
    )


def gen_commercial_screen(commercial, is_active=False):
    cls = "tab-panel active" if is_active else "tab-panel"
    if not commercial:
        body = (
            '          <tr><td class="title" colspan="3" '
            'style="text-align:center;color:var(--muted)">Available upon request.</td></tr>'
        )
    else:
        rows = []
        for c in commercial:
            rows.append(
                f'          <tr><td class="title">{esc(c.get("title", ""))}</td>'
                f'<td class="role">{esc(c.get("role", ""))}</td>'
                f'<td class="dir">{esc(c.get("brand", ""))}</td></tr>'
            )
        body = "\n".join(rows)
    return (
        f'\n    <div class="{cls}" id="commercial">\n'
        "      <table class=\"credits\">\n"
        "        <thead><tr><th>Title</th><th>Role</th><th>Brand</th></tr></thead>\n"
        "        <tbody>\n"
        + body + "\n"
        "        </tbody>\n"
        "      </table>\n"
        "    </div>\n    "
    )


def gen_theater_print(theater, footnotes_doc):
    resolved, active_footnotes = _theater_resolve(theater, footnotes_doc)
    rows = []
    for t in resolved:
        marker_html = (
            f'<sup>{esc(t["marker"])}</sup>' if t["marker"] else ""
        )
        rows.append(
            f'      <tr><td class="t">{esc(t["production"])}</td>'
            f'<td class="r">{esc(t["role"])}</td>'
            f'<td class="d">{esc(t["venue"])}{marker_html}</td></tr>'
        )

    foot_html = ""
    if active_footnotes:
        lines = [
            f'<span class="rs-theater-foot-row"><span class="m">{esc(n["marker"])}</span> {esc(n["long"])}</span>'
            for n in active_footnotes
        ]
        foot_html = (
            '\n    <p class="rs-theater-foot">'
            + " &nbsp; ".join(lines)
            + "</p>"
        )

    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Theater &middot; Sketch / Improv</h2>\n"
        "    <table class=\"rs-table rs-theater\">\n"
        + "\n".join(rows)
        + "\n    </table>"
        + foot_html
        + "\n  </div>\n  "
    )


# ---------- hero (slides + quotes) ----------

_reported_expired_slides = set()


def active_hero_slides(hero):
    """Hero slides with already-expired ones dropped.

    A slide may carry `expires: "YYYY-MM-DD"` to retire itself on that
    date (e.g. a show poster once the run closes). Slides whose date has
    already passed are omitted from the build entirely; ones still in the
    future are emitted with a data-expires attribute so the hero JS can
    retire them at runtime even if no rebuild happens in between.

    gen_hero_slides and gen_hero_quotes MUST both use this list — the
    rotator pairs slide N with quote N by index.
    """
    today = _dt.date.today()
    kept, dropped = [], []
    for s in hero["slides"]:
        raw = str(s.get("expires") or "").strip()
        if raw:
            try:
                if _dt.date.fromisoformat(raw) <= today:
                    dropped.append((s.get("photo") or s.get("video") or "?", raw))
                    continue
            except ValueError:
                print(f"  Warning: hero slide has an unparseable expires value {raw!r} "
                      "(want YYYY-MM-DD) - slide kept.")
        kept.append(s)
    # gen_hero_slides and gen_hero_quotes both call this; only report once.
    for src, when in dropped:
        key = (src, when)
        if key not in _reported_expired_slides:
            _reported_expired_slides.add(key)
            print(f"  Hero slide retired (expired {when}): {src}")
    return kept


def gen_hero_slides(hero):
    lines = []
    for s in active_hero_slides(hero):
        expires = str(s.get("expires") or "").strip()
        exp_attr = f' data-expires="{esc(expires)}"' if expires else ""
        video = s.get("video", "").strip() if s.get("video") else ""
        photo = s.get("photo", "").strip() if s.get("photo") else ""
        if video:
            # Note: no `loop` attribute - the JS rotator waits for the
            # video's `ended` event before advancing to the next slide,
            # so videos play their full length once. Muted by default
            # (autoplay requirement); the floating volume control unmutes.
            lines.append(
                f'    <video class="hero-slide"{exp_attr} muted playsinline preload="metadata">'
                f'<source src="{esc(video)}" type="video/mp4">'
                f'</video>'
            )
        else:
            lines.append(
                f'    <div class="hero-slide"{exp_attr} style="background-image:url(\'{esc(photo)}\')"></div>'
            )
    return "\n  <div class=\"hero-slides\" aria-hidden=\"true\">\n" + "\n".join(lines) + "\n  </div>\n  "


def gen_hero_quotes(hero):
    lines = []
    for s in active_hero_slides(hero):
        expires = str(s.get("expires") or "").strip()
        exp_attr = f' data-expires="{esc(expires)}"' if expires else ""
        lines.append(
            f"      <span{exp_attr}>{esc(s.get('quote_line_1', ''))}<br>"
            f"{esc(s.get('quote_line_2', ''))}</span>"
        )
    return "\n    <div class=\"hero-quotes\" aria-hidden=\"true\">\n" + "\n".join(lines) + "\n    </div>\n    "


# ---------- about (definition + pull quote) ----------

def gen_definition(about):
    d = about["definition"]
    items = "\n".join(f"          <li>{esc(e)}</li>" for e in d["entries"])

    # Speaker button next to Pronunciation. Uses an uploaded audio file
    # when set; otherwise falls back to the browser's SpeechSynthesis
    # voice speaking 'speak_text'. The audio-lines SVG matches the
    # Lucide icon set so it stylistically fits the training badges.
    audio_src = (d.get("pronunciation_audio") or "").strip()
    speak_text = (d.get("speak_text") or d.get("word") or "").strip()
    speaker_svg = (
        '<svg viewBox="0 0 24 24" aria-hidden="true">'
        '<line x1="2" x2="2" y1="10" y2="14"/>'
        '<line x1="6" x2="6" y1="6" y2="18"/>'
        '<line x1="10" x2="10" y1="9" y2="15"/>'
        '<line x1="14" x2="14" y1="6" y2="18"/>'
        '<line x1="18" x2="18" y1="11" y2="13"/>'
        '<line x1="22" x2="22" y1="10" y2="14"/>'
        '</svg>'
    )
    speaker_btn = (
        '<button class="pron-play" type="button"'
        ' aria-label="Hear pronunciation"'
        f' data-audio="{esc(audio_src)}"'
        f' data-text="{esc(speak_text)}">'
        f'{speaker_svg}</button>'
    )

    return (
        "\n      <div class=\"def\">\n"
        f'        <h3>{esc(d["word"])} <small style="color:var(--muted);font-size:14px;font-weight:400">({esc(d["part_of_speech"])})</small></h3>\n'
        f'        <div class="pron">Pronunciation: {esc(d["pronunciation"])} {speaker_btn}</div>\n'
        "        <ol>\n"
        + items + "\n"
        "        </ol>\n"
        "      </div>\n      "
    )


def gen_pull_quote(about):
    """Pull-quote slider. Supports legacy single-object (pull_quote) and
    new list form (pull_quotes). With one item, renders static; with 2+,
    renders as a slider that JS rotates every 7s with a left-slide
    transition (see pullQuoteRotate in the main <script>)."""
    items = about.get("pull_quotes")
    if not items:
        single = about.get("pull_quote")
        items = [single] if single else []
    if not items:
        return "\n      <!-- no pull quotes configured -->\n      "

    multi = len(items) > 1
    slides_class = "pullquote-slides" + (" multi" if multi else " single")
    slide_html = []
    for i, q in enumerate(items):
        active = " active" if i == 0 else ""
        attribution = (q.get("attribution") or "").strip()
        cite_html = (
            f"\n            <cite>&mdash; {esc(attribution)}</cite>"
            if attribution else ""
        )
        slide_html.append(
            f'          <div class="pullquote-slide{active}">\n'
            f'            <p>{esc(q["text"])}</p>{cite_html}\n'
            f'          </div>'
        )
    return (
        "\n      <div class=\"pullquote\">\n"
        f'        <div class="{slides_class}">\n'
        + "\n".join(slide_html) + "\n"
        "        </div>\n"
        "      </div>\n      "
    )


# ---------- panels ----------

def gen_physical(p):
    items = [
        ("Age Range:", p["age_range"]),
        ("Height:", p["height"]),
        ("Eyes:", p["eyes"]),
        ("Hair:", p["hair"]),
        ("Tattoos:", p["tattoos"]),
        ("Piercings:", p["piercings"]),
    ]
    lis = "\n".join(
        f'          <li><span class="label">{esc(k)}</span> {esc(v)}</li>'
        for k, v in items
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Physical</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_languages(langs):
    lis = "\n".join(
        f'          <li><span class="label">{esc(l["name"])}</span><span class="sub">{esc(l["level"])}</span></li>'
        for l in langs
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Languages</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_languages_print(langs):
    parts = " &middot; ".join(f"{esc(l['name'])} ({esc(l['level'])})" for l in langs)
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Languages</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {parts}\n    </div>\n"
        "  </div>\n  "
    )


def gen_measurements(m):
    items = [
        ("Shoe:", m["shoe"]),
        ("Shirt:", m["shirt"]),
        ("Coat:", m["coat"]),
        ("Neck:", m["neck"]),
        ("Sleeve:", m["sleeve"]),
        ("Hat:", m["hat"]),
    ]
    lis = "\n".join(
        f'          <li><span class="label">{esc(k)}</span> {esc(v)}</li>'
        for k, v in items
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Measurements</h4>\n"
        "        <ul>\n"
        + lis + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_licensing(lic):
    docs = "\n".join(f"          <li>{esc(d)}</li>" for d in lic["documents"])
    extras = (
        f'          <li><span class="label">Union:</span><span class="sub">{esc(lic["union"])}</span></li>\n'
        f'          <li><span class="label">Local Hire:</span><span class="sub">{esc(lic["local_hire"])}</span></li>'
    )
    return (
        "\n      <div class=\"panel col-3\">\n"
        "        <h4>Licensing &amp; Hire</h4>\n"
        "        <ul>\n"
        + docs + "\n"
        + extras + "\n"
        "        </ul>\n"
        "      </div>\n      "
    )


def gen_licensing_print(lic):
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Licensing</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {' &middot; '.join(esc(d) for d in lic['documents'])}\n    </div>\n"
        "  </div>\n  "
    )


def gen_skills(skills_str):
    return (
        "\n      <div class=\"panel\">\n"
        "        <h4>Key Skills</h4>\n"
        f"        <p>\n          {esc(skills_str)}\n        </p>\n"
        "      </div>\n      "
    )


def gen_skills_print(skills_str):
    return (
        "\n  <div class=\"rs-section\">\n"
        "    <h2>Special Skills</h2>\n"
        f"    <div class=\"rs-skills-list\">\n      {esc(skills_str)}\n    </div>\n"
        "  </div>\n  "
    )


def gen_favorite_films(films):
    lis = "\n".join(
        f'              <li>{esc(f["title"])} <span class="sub">{esc(f["director"])}, {esc(f["year"])}</span></li>'
        for f in films
    )
    return (
        "\n          <div class=\"panel\">\n"
        "            <h4>Favorite Films</h4>\n"
        "            <ul>\n"
        + lis + "\n"
        "            </ul>\n"
        "          </div>\n          "
    )


def gen_inspirations(insp):
    lis = "\n".join(f"              <li>{esc(n)}</li>" for n in insp)
    return (
        "\n          <div class=\"panel\">\n"
        "            <h4>Inspirations</h4>\n"
        "            <ul>\n"
        + lis + "\n"
        "            </ul>\n"
        "          </div>\n          "
    )


def gen_print_stats(panels):
    p = panels["physical"]
    m = panels["measurements"]
    cells = [
        ("Height", p["height"]),
        ("Eyes", p["eyes"]),
        ("Hair", p["hair"]),
        ("Age Range", p["age_range"]),
        ("Shoe", m["shoe"]),
        ("Suit", f"{m['coat']} / {m['shirt']} / {m['neck']}"),
    ]
    divs = "\n".join(
        f"    <div><strong>{esc(label)}</strong>{esc(value)}</div>"
        for label, value in cells
    )
    return (
        "\n  <div class=\"rs-stats\">\n"
        + divs + "\n"
        "  </div>\n  "
    )


# ---------- contact (email, socials, reel) ----------

# SVG icons for the supported social platforms.
SOCIAL_ICONS = {
    # Stroke-based Instagram glyph (rounded square + lens + flash dot),
    # inset to x=3..21 so it doesn't crowd the pill's inner edge the way
    # the old edge-to-edge filled path did.
    "Instagram": '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><line x1="16.9" y1="7.1" x2="17" y2="7.1"/></svg>',
    "Letterboxd": '<svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor"><circle cx="6" cy="12" r="3.2"/><circle cx="12" cy="12" r="3.2" opacity=".6"/><circle cx="18" cy="12" r="3.2"/></svg>',
    # Boxed wordmarks: the border rect is inset to x=2.5..21.5 and the
    # label uses textLength so 4-char "IMDb" is scaled to fit instead of
    # overflowing past the right border (the old font-size=7 clipped the b).
    "IMDb": '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2.5" y="6.5" width="19" height="11" rx="1.5" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="12" y="14.9" text-anchor="middle" textLength="14" lengthAdjust="spacingAndGlyphs" font-size="7" font-weight="900" fill="currentColor" font-family="Montserrat, sans-serif">IMDb</text></svg>',
    "Actors Access": '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="2.5" y="6.5" width="19" height="11" rx="1.5" fill="none" stroke="currentColor" stroke-width="1.5"/><text x="12" y="15" text-anchor="middle" textLength="9" lengthAdjust="spacingAndGlyphs" font-size="8" font-weight="900" fill="currentColor" font-family="Montserrat, sans-serif">AA</text></svg>',
    "Email": '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><rect x="2.5" y="5" width="19" height="14" rx="2"/><path d="m3 6.5 9 6 9-6"/></svg>',
}


def mailto_url(email, subject=""):
    """Build a mailto: URL with an optional prefilled Subject so inbound
    mail from the site is instantly identifiable. Returns a bare mailto:
    when no subject is configured."""
    email = (email or "").strip()
    # Accept either "frank@x.cc" or an already-prefixed "mailto:frank@x.cc"
    addr = email[7:] if email.lower().startswith("mailto:") else email
    subject = (subject or "").strip()
    if not subject:
        return f"mailto:{addr}"
    return f"mailto:{addr}?subject={urllib.parse.quote(subject)}"


def gen_socials(socials, email_subject=""):
    items = []
    for s in socials:
        platform = s["platform"]
        url = s["url"]
        # Stamp the configured Subject onto the Email pill. Skip if the
        # author already hand-wrote their own query string.
        if url.lower().startswith("mailto:") and "?" not in url:
            url = mailto_url(url, email_subject)
        icon = SOCIAL_ICONS.get(platform, "")
        external = "" if url.startswith("mailto:") else ' target="_blank" rel="noopener"'
        items.append(
            f'          <a href="{esc(url)}"{external} aria-label="{esc(platform)}" title="{esc(platform)}">\n'
            f'            {icon}\n'
            f'          </a>'
        )
    return (
        "\n        <div class=\"socials\">\n"
        + "\n".join(items) + "\n"
        "        </div>\n        "
    )


def embed_url(url):
    """Normalize a YouTube/Vimeo link to its embeddable form.

    People paste whatever the browser address bar shows, but a watch or
    share URL cannot be framed - YouTube and Vimeo both refuse it, so the
    reel would render as a blank box. Convert the common shapes; anything
    already an /embed/ or player. URL (or an unrecognized host) passes
    through untouched.
    """
    u = (url or "").strip()
    if not u:
        return ""

    # youtu.be/VIDEOID
    m = re.match(r"https?://(?:www\.)?youtu\.be/([\w-]+)", u)
    if m:
        return f"https://www.youtube.com/embed/{m.group(1)}"

    # youtube.com/watch?v=VIDEOID  (and /shorts/, /live/)
    m = re.match(r"https?://(?:www\.)?youtube\.com/watch\?(?:.*&)?v=([\w-]+)", u)
    if m:
        return f"https://www.youtube.com/embed/{m.group(1)}"
    m = re.match(r"https?://(?:www\.)?youtube\.com/(?:shorts|live)/([\w-]+)", u)
    if m:
        return f"https://www.youtube.com/embed/{m.group(1)}"

    # vimeo.com/VIDEOID  (optionally /HASH for unlisted videos)
    m = re.match(r"https?://(?:www\.)?vimeo\.com/(\d+)(?:/(\w+))?", u)
    if m:
        vid, h = m.group(1), m.group(2)
        return f"https://player.vimeo.com/video/{vid}" + (f"?h={h}" if h else "")

    return u


def gen_reel(contact):
    r = contact["reel"]
    url = (r.get("url") or "").strip()
    fil = (r.get("file") or "").strip()

    # `source` makes the choice explicit so the unused field can stay
    # populated. Fall back to the old url-wins-then-file behaviour when
    # source is absent (older data files).
    source = str(r.get("source") or "").strip().lower()
    if source not in {"file", "embed", "none"}:
        source = "embed" if url else ("file" if fil else "none")

    if source == "embed" and url:
        return (
            f'\n      <div class="reel">\n'
            f'        <iframe src="{esc(embed_url(url))}" title="Acting reel" '
            f'allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>\n'
            f'      </div>\n      '
        )
    if source == "file" and fil:
        return (
            f'\n      <div class="reel">\n'
            f'        <video controls playsinline preload="metadata"><source src="{esc(fil)}" type="video/mp4"></video>\n'
            f'      </div>\n      '
        )
    return (
        f'\n      <div class="reel">\n'
        f'        <span>{esc(r.get("placeholder", "Reel coming soon"))}</span>\n'
        f'      </div>\n      '
    )


def gen_contact_section(contact):
    cs = contact.get("contact_section", {})
    heading = cs.get("heading", "Let's Work")
    body = cs.get("body", "")
    email = contact["email"]
    href = mailto_url(email, contact.get("email_subject", ""))
    return (
        '\n    <span class="kicker" style="font-family:\'Montserrat\',sans-serif;font-size:11px;color:var(--accent);letter-spacing:.3em;text-transform:uppercase">04 &mdash; Contact</span>\n'
        f'    <h2 style="margin-top:8px">{esc(heading)}</h2>\n'
        f'    <p style="color:var(--muted);max-width:520px;margin:14px auto 0">\n      {esc(body)}\n    </p>\n'
        f'    <a class="email" href="{esc(href)}">{esc(email)}</a>\n  '
    )


# ---------- site (SEO / OG / GA4) ----------

def gen_site_meta(site):
    s = site["seo"]
    return (
        f'\n<title>{esc(s["title"])}</title>\n'
        f'<meta name="description" content="{esc(s["description"])}">\n'
        f'<meta name="author" content="{esc(s["author"])}">\n'
        f'<meta name="theme-color" content="#2c2e3d">\n'
        f'<meta name="robots" content="{esc(s["robots"])}">\n'
        f'<link rel="canonical" href="{esc(s["canonical_url"])}">\n'
    )


def gen_og_tags(site):
    og = site["og"]
    tw = site["twitter"]
    canonical = site["seo"]["canonical_url"]
    return (
        f'\n<meta property="og:type" content="{esc(og["type"])}">\n'
        f'<meta property="og:site_name" content="{esc(og["site_name"])}">\n'
        f'<meta property="og:title" content="{esc(og["title"])}">\n'
        f'<meta property="og:description" content="{esc(og["description"])}">\n'
        f'<meta property="og:url" content="{esc(canonical)}">\n'
        f'<meta property="og:image" content="{esc(og["image"])}">\n'
        f'<meta property="og:image:secure_url" content="{esc(og["image"])}">\n'
        f'<meta property="og:image:width" content="1200">\n'
        f'<meta property="og:image:height" content="630">\n'
        f'<meta property="og:image:alt" content="{esc(og["image_alt"])}">\n'
        f'<meta property="og:locale" content="{esc(og["locale"])}">\n'
        f'<meta property="profile:first_name" content="Frank">\n'
        f'<meta property="profile:last_name" content="Rizzo">\n'
        f'<meta property="profile:gender" content="male">\n'
        '\n<!-- Twitter / X -->\n'
        f'<meta name="twitter:card" content="{esc(tw["card"])}">\n'
        f'<meta name="twitter:title" content="{esc(og["title"])}">\n'
        f'<meta name="twitter:description" content="{esc(og["description"])}">\n'
        f'<meta name="twitter:image" content="{esc(og["image"])}">\n'
        f'<meta name="twitter:image:alt" content="{esc(og["image_alt"])}">\n'
    )


def gen_ga4(site):
    ga4 = site["analytics"]["ga4_id"]
    return (
        f'\n<script async src="https://www.googletagmanager.com/gtag/js?id={esc(ga4)}"></script>\n'
        '<script>\n'
        '  window.dataLayer = window.dataLayer || [];\n'
        '  function gtag(){dataLayer.push(arguments);}\n'
        "  gtag('js', new Date());\n"
        f"  gtag('config', '{esc(ga4)}', {{ 'anonymize_ip': true }});\n"
        '</script>\n'
    )


def gen_menu(site):
    items = site.get("menu", [])
    if not items:
        return "\n  <nav class=\"nav\"></nav>\n  "
    links = "\n".join(
        f'    <a href="{esc(m["url"])}">{esc(m["label"])}</a>'
        for m in items
    )
    return "\n  <nav class=\"nav\">\n" + links + "\n  </nav>\n  "


# Map of section toggle key → CSS selector to hide when false.
# When you add a new toggleable section, drop the (key, selector)
# pair here AND expose the toggle in admin/config.yml > Sections.
SECTION_SELECTORS = {
    "about":           "#about",
    "profile_bio":     ".profile-bio",
    "profile_gallery": ".headshot-gallery",
    "profile_socials": ".socials",
    "resume":          "#resume",
    "credits":         "#credits",
    "reel":            "#reel-wrapper",
    "contact":         "#contact",
}


def gen_section_visibility(site):
    """Emit a <style> block with display:none rules for any section
    toggled off in site.yml. Renders in <head> so it applies before
    body paints - zero flicker."""
    sections = site.get("sections") or {}
    hidden_rules = []
    for key, selector in SECTION_SELECTORS.items():
        if sections.get(key, True) is False:
            hidden_rules.append(f"{selector}{{display:none!important}}")
    if not hidden_rules:
        return "\n<!-- all sections visible -->\n"
    return "\n<style>" + "".join(hidden_rules) + "</style>\n"


def gen_footer(site):
    f = site.get("footer", {})
    template = f.get("text", "© {{year}} Rizzo.cc")
    show_version = f.get("show_version", True)

    # Replace {{year}} with the dynamic year span (filled by JS at runtime)
    rendered = esc(template).replace("{{year}}", '<span id="yr"></span>')

    # Append version chip if enabled (replaces {{version}} if present, else
    # appends as the next visible element)
    if show_version:
        version_html = f'<span class="ver">{esc(SITE_VERSION)}</span>'
        if "{{version}}" in rendered:
            rendered = rendered.replace("{{version}}", version_html)
        else:
            rendered = rendered.rstrip() + " " + version_html
    else:
        rendered = rendered.replace("{{version}}", "")

    return f"\n<footer>\n  {rendered}\n</footer>\n"


# ---------- main ----------

def _load_list(path):
    """Load a YAML file shaped like `entries: [...]` and return that list.
    Returns [] if the file is missing or empty."""
    if not path.exists():
        return []
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return data.get("entries", []) or []


def _load_obj(path):
    """Load a YAML file and return its top-level dict.
    Returns {} if the file is missing or empty."""
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def main():
    # Each collection's data is split across multiple per-topic files so
    # Decap's sidebar lists Film / TV / Theater / Physical / Skills / Menu
    # / Footer / etc. as separate clickable entries instead of one giant
    # blob. The dicts here re-assemble the old shapes so the gen_*
    # functions don't need to change.

    # ---- Credits ----------------------------------------------------
    tabs_doc = _load_obj(DATA / "credits-tabs.yml")
    theater_footnotes_doc = _load_obj(DATA / "theater-footnotes.yml")
    credits = {
        "film": _load_list(DATA / "film.yml"),
        "tv": _load_list(DATA / "tv.yml"),
        "theater": _load_list(DATA / "theater.yml"),
        "commercial": _load_list(DATA / "commercial.yml"),
        "tab_visibility": tabs_doc.get("tabs") or {},
        "theater_footnotes": theater_footnotes_doc,
    }

    # ---- Stats / Skills / Influences -------------------------------
    panels = {
        "physical":       _load_obj(DATA / "physical.yml"),
        "measurements":   _load_obj(DATA / "measurements.yml"),
        "languages":      _load_list(DATA / "languages.yml"),
        "licensing":      _load_obj(DATA / "licensing.yml"),
        "skills":         _load_obj(DATA / "skills.yml").get("text", ""),
        "favorite_films": _load_list(DATA / "favorite-films.yml"),
        "inspirations":   _load_list(DATA / "inspirations.yml"),
    }

    # ---- Contact / Socials / Reel ----------------------------------
    contact = {
        **_load_obj(DATA / "contact.yml"),         # email + contact_section
        "socials": _load_list(DATA / "socials.yml"),
        "reel":    _load_obj(DATA / "reel.yml"),
    }

    # ---- Site Settings ---------------------------------------------
    seo_doc = _load_obj(DATA / "seo.yml")
    site = {
        "seo":       seo_doc.get("seo", {}),
        "og":        seo_doc.get("og", {}),
        "twitter":   seo_doc.get("twitter", {}),
        "favicon":   _load_obj(DATA / "favicon.yml"),
        "analytics": _load_obj(DATA / "analytics.yml"),
        "menu":      _load_list(DATA / "menu.yml"),
        "footer":    _load_obj(DATA / "footer.yml"),
        "sections":  _load_obj(DATA / "sections.yml"),
    }

    # ---- Other single-file inputs ----------------------------------
    training = yaml.safe_load((DATA / "training.yml").read_text(encoding="utf-8"))
    hero = yaml.safe_load((DATA / "hero.yml").read_text(encoding="utf-8"))
    about = yaml.safe_load((DATA / "about.yml").read_text(encoding="utf-8"))
    headshots = _load_obj(DATA / "headshots.yml")
    print_cfg = _load_obj(DATA / "print-resume.yml")
    html = INDEX.read_text(encoding="utf-8")

    # Head: SEO meta, OG, GA4
    html = replace_block(html, "site-meta", gen_site_meta(site))
    html = replace_block(html, "og-tags", gen_og_tags(site))
    html = replace_block(html, "ga4", gen_ga4(site))

    # Chrome: top-nav menu + footer + section visibility
    html = replace_block(html, "menu", gen_menu(site))
    html = replace_block(html, "footer", gen_footer(site))
    html = replace_block(html, "section-visibility", gen_section_visibility(site))

    # Profile: headshot + gallery thumbnails
    html = replace_block(html, "headshot-main", gen_headshot_main(headshots))
    html = replace_block(html, "headshot-gallery", gen_headshot_gallery(headshots))

    # Bio + Credits + Training
    html = replace_block(html, "bio", gen_bio())
    html = replace_block(html, "training", gen_training_screen(training))
    html = replace_block(html, "print-training", gen_training_print(training))
    # Tabs strip — only includes visible tabs; first visible gets active state
    html = replace_block(html, "credits-tabs", gen_credits_tabs(credits))

    # Per-tab panels: render only when the tab is visible. The build script's
    # replace_block fills with empty content so the panel <div> disappears.
    def panel_or_hidden(slug, gen, *args):
        visible_slugs = {s for s, _ in _visible_tabs(credits)}
        if slug not in visible_slugs:
            return "\n    "
        return gen(*args, is_active=_is_first_visible(credits, slug))

    html = replace_block(html, "film-credits",
                         panel_or_hidden("film", gen_film_screen, credits["film"]))
    html = replace_block(html, "tv-credits",
                         panel_or_hidden("tv", gen_tv_screen, credits["tv"]))
    html = replace_block(html, "theater-credits",
                         panel_or_hidden("theater", gen_theater_screen, credits["theater"], credits["theater_footnotes"]))
    html = replace_block(html, "commercial-credits",
                         panel_or_hidden("commercial", gen_commercial_screen, credits.get("commercial", [])))

    # Printed PDF resume always uses all sections except Commercial
    # (Commercial is intentionally omitted from print).
    html = replace_block(html, "print-film-credits", gen_film_print(credits["film"]))
    html = replace_block(html, "print-tv-credits", gen_tv_print(credits["tv"]))
    html = replace_block(html, "print-theater-credits", gen_theater_print(credits["theater"], credits["theater_footnotes"]))

    # Hero
    html = replace_block(html, "hero-slides", gen_hero_slides(hero))
    html = replace_block(html, "hero-quotes", gen_hero_quotes(hero))

    # About
    html = replace_block(html, "rizzo-definition", gen_definition(about))
    html = replace_block(html, "pull-quote", gen_pull_quote(about))

    # Resume panels
    html = replace_block(html, "physical", gen_physical(panels["physical"]))
    html = replace_block(html, "languages", gen_languages(panels["languages"]))
    html = replace_block(html, "print-languages", gen_languages_print(panels["languages"]))
    html = replace_block(html, "measurements", gen_measurements(panels["measurements"]))
    html = replace_block(html, "licensing", gen_licensing(panels["licensing"]))
    html = replace_block(html, "print-licensing", gen_licensing_print(panels["licensing"]))
    html = replace_block(html, "skills", gen_skills(panels["skills"]))
    html = replace_block(html, "print-skills", gen_skills_print(panels["skills"]))
    html = replace_block(html, "favorite-films", gen_favorite_films(panels["favorite_films"]))
    html = replace_block(html, "inspirations", gen_inspirations(panels["inspirations"]))
    html = replace_block(html, "print-stats", gen_print_stats(panels))

    # Contact / socials / reel
    html = replace_block(html, "socials",
                         gen_socials(contact["socials"], contact.get("email_subject", "")))
    html = replace_block(html, "reel", gen_reel(contact))
    html = replace_block(html, "contact-section", gen_contact_section(contact))

    # Printed resume: pick the density tier that keeps it on ONE page.
    tier, est_pt, forced = resolve_print_density(credits, training, panels, print_cfg)
    html = apply_print_density_class(html, tier)

    INDEX.write_text(html, encoding="utf-8")
    print(f"Wrote {INDEX.relative_to(ROOT)}")

    # Report the one-page budget so growth is visible in the build log.
    pct = est_pt / PRINT_BUDGET_PT * 100
    how = "forced via print-resume.yml" if forced else "auto"
    # ASCII only in build output - the Windows console codepage mangles
    # em dashes and box-drawing characters.
    print(
        f"Print resume: density tier {tier} ({how}) - "
        f"est. {est_pt:.0f}pt of {PRINT_BUDGET_PT:.0f}pt available ({pct:.0f}% full)"
    )
    if est_pt > PRINT_BUDGET_PT:
        over = est_pt - PRINT_BUDGET_PT
        print(
            "\n"
            "  !! ONE-PAGE BUDGET EXCEEDED !!\n"
            f"  The printed resume is an estimated {over:.0f}pt "
            f"({over / 72:.2f}in) too tall even at the tightest tier.\n"
            "  It will likely spill onto a second page. To fix, trim content\n"
            "  (Special Skills is usually the easiest - aim for 8-12 items),\n"
            "  or add another density lever to the .rs-d4 CSS block.\n"
        )
    elif not forced and tier >= 3:
        print(
            f"  Note: tier {tier} is in effect, so the footer rizzo.cc/email "
            "block is hidden and\n  the QR code has moved into the header. "
            "Trim content to get back to tier 1-2."
        )


if __name__ == "__main__":
    main()
